# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_remove_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(max_length=100),
        ),
    ]
